// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAjBBVdd473Oce1YfNNd6MigRXlDxwe6-Q',
    appId: '1:478766196608:web:9f2f1d10264d489242c365',
    messagingSenderId: '478766196608',
    projectId: 'note-304b6',
    authDomain: 'note-304b6.firebaseapp.com',
    storageBucket: 'note-304b6.firebasestorage.app',
    measurementId: 'G-KQ8SK4SE18',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCm8BMbel0GIWbWp2ODioVaQQj_pxmBDQQ',
    appId: '1:478766196608:android:e656300650bc5b6642c365',
    messagingSenderId: '478766196608',
    projectId: 'note-304b6',
    storageBucket: 'note-304b6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAe2wH3ewm-AvtrYnrejRz5rwZeJG6oogw',
    appId: '1:478766196608:ios:fc68b4a40234426542c365',
    messagingSenderId: '478766196608',
    projectId: 'note-304b6',
    storageBucket: 'note-304b6.firebasestorage.app',
    iosBundleId: 'com.example.noteCalendar',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAe2wH3ewm-AvtrYnrejRz5rwZeJG6oogw',
    appId: '1:478766196608:ios:fc68b4a40234426542c365',
    messagingSenderId: '478766196608',
    projectId: 'note-304b6',
    storageBucket: 'note-304b6.firebasestorage.app',
    iosBundleId: 'com.example.noteCalendar',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAjBBVdd473Oce1YfNNd6MigRXlDxwe6-Q',
    appId: '1:478766196608:web:15c6e456a52d76a042c365',
    messagingSenderId: '478766196608',
    projectId: 'note-304b6',
    authDomain: 'note-304b6.firebaseapp.com',
    storageBucket: 'note-304b6.firebasestorage.app',
    measurementId: 'G-9VEHLREP8D',
  );
}
